### ISSUE TITLE
export to csv button on grid not working in Internet Explorer

### ISSUE THREAD

**Issue by psDevUK** [ironmansoftware/universal-dashboard#1004]
Hi when the new refresh button and export to csv buttons were introduced to the grid, I have noticed the export to csv does not work in Internet Explorer please can this be fixed. Thanks

**Comment by AlonGvili** [comment]
I think the problem is ie 11 dont support download attribute on the <a> tag

**Comment by psDevUK** [comment]
@AlonGvili and @adamdriscoll I seen a JS fix for this, so new question how can you run a JS file or script inside a universal dashboard?

**Comment by psDevUK** [comment]
Seen a fix listed here https://github.com/ChenWenBrian/FileSaver.js#examples but how would one go about implementing it?

**Comment by adamdriscoll** [comment]
@psDevUK You will need to do the following. 

Add that fileSaver.js file to the components folder: https://github.com/ironmansoftware/universal-dashboard/tree/master/src/UniversalDashboard.Materialize/Components

Update the ud-grid.jsx to import the JS file: https://github.com/ironmansoftware/universal-dashboard/blob/master/src/UniversalDashboard.Materialize/Components/ud-grid.jsx#L9

Update the export function of ud-grid.jsx to use that file saver function rather than the lines 208-217 in this file: https://github.com/ironmansoftware/universal-dashboard/blob/master/src/UniversalDashboard.Materialize/Components/ud-grid.jsx#L208

Check out the contribution guide on how to build it: https://github.com/ironmansoftware/universal-dashboard/blob/master/docs/contributing.md

You can also use this document to see how to debug the component: https://github.com/ironmansoftware/universal-dashboard/blob/master/docs/working-on-a-component.md

**Comment by psDevUK** [comment]
@adamdriscoll you are a legend, I will tinker and report back 👍

**Comment by AlonGvili** [comment]
do this
cd to UniversalDashboard.Materialize

run this command
```
npm install file-saver --save
```

in line 10 add: import { saveAs } from 'file-saver'
 https://github.com/ironmansoftware/universal-dashboard/blob/master/src/UniversalDashboard.Materialize/Components/ud-grid.jsx#L10

remove the code 

```js
        var element = document.createElement('a');
        element.setAttribute('href', 'data:text/plain;charset=utf-8,' + encodeURIComponent(csv));
        element.setAttribute('download', 'export.csv');
      
        element.style.display = 'none';
        document.body.appendChild(element);
      
        element.click();
      
        document.body.removeChild(element);
```

Add this code
```js

var blob = new Blob([csv], {type: "text/csv;charset=utf-8"});
saveAs(blob, "export.csv",{ autoBom: true })

```

Run the build command and test the changes

I test this on IE11 works great

**Comment by psDevUK** [comment]
Dear @AlonGvili you just saved me a stupid amount of research and tinkering. Thank you so much. I have completed the steps you advised. Now reading through steps of re-compiling.  Seriously thanks so much this will be a major game changer for me at work...ok less typing I need to now re-compile....Thanks again @AlonGvili and @adamdriscoll for providing the files and steps needed.  👍

**Comment by psDevUK** [comment]
Hi @AlonGvili well I finally managed to run the build.ps1 I did get some red text on my screen...then imported the module from universal-dashboard-master\src\UniversalDashboard\UniversalDashboard.psm1 ran a simple get-process to grid in firefox, and export button worked, then tried IE11 and nothing seemed to happen...so I'm wondering what went wrong? I will look at this some more now and hopefully get this working in IE11 like you...(fingers crossed)

**Comment by AlonGvili** [comment]
@psDevUK  if it working for you can you close this issue?

**Comment by psDevUK** [comment]
Feel like a right plonker, even though you have given me the code, I still seem to be struggling to get this working

**Comment by psDevUK** [comment]
Awesome @AlonGvili you deserve more than a high-five for this, thank you @adamdriscoll for explaining the steps I needed to take and @AlonGvili for providing the code, and having the patience to explain even further.  I will PR the changes back. Thanks guys
