### ISSUE TITLE
Invoke-UDRedirect

### ISSUE THREAD

**Issue by adamdriscoll** [ironmansoftware/universal-dashboard#125]
Redirects a user from any endpoint. 

Invoke-UDRedirect -Name <PageName> -ArgumentList <ArugmentsForPage>
Invoke-UDRedirect -Url <Url>

**Comment by apetitjean** [comment]
That would be awesome!!!

**Comment by apetitjean** [comment]
@adamdriscoll, how can I do a URL redirection currently (meanwhile Invoke-UDRedirect is implemented)?

**Comment by apetitjean** [comment]
up! ;-)

**Comment by Phyziik** [comment]
Up? What do you mean? Function isn't in 1.6.1, am I wrong? (I'm waiting for this too!!)

**Comment by apetitjean** [comment]
It maybe awkward I admit it... But I just wanted @adamdriscoll if possible to answer about how to do a workaround meanwhile.

**Comment by Phyziik** [comment]
oh, so you meant "Bump"! Thought so. Well I'm glad you did, because I'm sort of using a work around for my buttons, with UDElements, but they are not as fluid (loading udelement btn are longer than loading plain UDButtons). So, I too am looking for either a better workaround, or an update on which version will contain this!

**Comment by apetitjean** [comment]
Great! Thanks Adam! Will try that!

2018-05-09 16:22 GMT+02:00 Adam Driscoll <notifications@github.com>:

**Comment by adamdriscoll** [comment]
This has been implemented in 1.7.0.
