### ISSUE TITLE
Background tasks (one time “UDEndpointSchedule”?)

### ISSUE THREAD

**Issue by augiaugi** [ironmansoftware/universal-dashboard#1393]
I came across the following need:

execute a script in the background and update Cache variables and sync elements.
Does it makes sense to have a -OneTime parameter in the UDEndpointSchedule? (does not really fit with the schedule name).
Or should this be solved by using Powershell Jobs?

This maybe can also relate to this thread (-OneTime and manually trigger if required)

https://forums.universaldashboard.io/t/manual-trigger-of-scheduled-endpoint/1036

In order of “manually” trigger it could make sense to have a -Manually (no autom. execution) parameter

see forum thread: https://forums.universaldashboard.io/t/background-tasks-one-time-udendpointschedule/1764

**Comment by adamdriscoll** [comment]
This issue has been mentioned on **Ironman Software Forums**. There might be relevant details there:

https://forums.universaldashboard.io/t/returning-status-before-end-of-endpoint/2057/9

**Comment by LxLeChat** [comment]
I love this idea, and indeed the thread is realated !
What could be awsome is if we could lauchn this kind of endpoint from within another endpoint !

Other thing: passing parameters ! (like a reguler REST endpoint! )
On my side i have some long running endpoints (creating some and setting some stuff in exchange online) and the only thing that changes for example is the idendity ... that's why i'm talking about parameters !

**Comment by adamdriscoll** [comment]
This issue has been mentioned on **Ironman Software Forums**. There might be relevant details there:

https://forums.universaldashboard.io/t/controlling-scheduler-for-endpoint/2487/25

**Comment by augiaugi** [comment]
@adamdriscoll in order to your answer in the above forum thread, this can be done using the new UDEndpoint commands
