### ISSUE TITLE
Attempt to use the new hardcoded classs definitions in themeservice causes UD to crash.

### ISSUE THREAD

**Issue by BoSen29** [ironmansoftware/universal-dashboard#1471]
#### Describe the Issue
Copy pasting the theme from Default to DarkDefault caused my UD to run in "demomode".
Seems like the new definitions in themeservice.cs fails on non default themes.

#### To Reproduce
Steps to reproduce the behavior: (Example)
1. Copy paste UDTab definitions from default theme to DarkDefault
2. Load dashboard

#### Expected behavior
Function identical to Default Theme

#### Version Information
- **2019 Server**:
- **5.1**:
- **UD Enterprise 2.8.2**:
- **UD Hosting Method**: IIS

**Comment by adamdriscoll** [comment]
It's because FontFamily was being set to $null. The default theme defines a $FontFamily variable at the top of the theme. The DefaultDark wasn't doing this. This caused the FontFamily value to be $null and in turn caused the ThemeService to barf. I'm adding a check for null that doesn't cause the theme service to fail as well as adding the font family to the DefaultDark theme.
