### ISSUE TITLE
Modified login window?

### ISSUE THREAD

**Issue by oitptobbe** [ironmansoftware/universal-dashboard#155]
Would it be possible to modify the login window to allow 2FA/MFA integration?
For instance we would like to send a sms / push notification to the users device if they want to login.
We have working powershell code for this from another system.

But it would require us to after login, transfer to a new page where they are required to enter a response.

**Comment by adamdriscoll** [comment]
It's not currently supported but others have asked for this as well. Will look at it in the next release.

**Comment by adamdriscoll** [comment]
Related: #21

**Comment by oitptobbe** [comment]
@adamdriscoll Another good thing would be to be able to include a "forgot password" link on the login page. We would be satisfied with just being able to redirect them to another page (that doesn't require them to be logged in).

**Comment by itfranck** [comment]
While at it, speaking of Login Window, it would be nice to have an Auto-redirect to provider sign-in page therefore bypassing the login page entirely (maybe through a flag)

We do have such an application on Azure which if the user is not logged in, the page to sign-in is presented directly instead of having to click on the "Sign-in" button then be redirected to the second page.

**Comment by adamdriscoll** [comment]
Rolling into #21
