### ISSUE TITLE
Pass in variables into New-UDTable Endpoint

### ISSUE THREAD

**Issue by ericclaus14** [ironmansoftware/universal-dashboard#240]
Greetings,

I am trying to dynamically create New-UDTable by iterating through an array, using foreach, containing values to be passed into each New-UDTable as a variable. I'm not seeing a way to pass in a variable to the Endpoint script block, however. Is this possible, and if so, what is the best way to go about this?

Below is an excerpt from my script. In this case, I'm trying to iterate through a list of VMs and the create a table for each one using the output of a function Show-BackupStatusHistory which is dot sourced in the EndpointInitializationScript block. I'd like to get the $VM variable passed into the Endpoint block each time the foreach loops.

```
$dashboard = New-UDDashboard -Title "Cyrus Backup Solution" -Content {
    $VMs = @(
                "V:\VM_Backup\AD3",
                "V:\VM_Backup\Centurion1",
                "V:\VM_Backup\CyrusClient1",
                "V:\VM_Backup\Dokuwiki1") 

    foreach ($VM in $VMs) {
        New-UDTable -Title "$VM VM Backup History" -Headers @("Name","CreationTime","LastModified","Size") -Endpoint {
            
            (Show-BackupStatusHistory -BackupDir "$VM") | 
                Out-UDTableData -Property @("Name","CreationTime","LastModified","Size")

        } -Style highlight -DateTimeFormat "LLLL" -AutoRefresh
    }
} -EndpointInitializationScript {
    . "C:\Scripts\Cyrus-Backup-Server\Show-BackupStatus.ps1"
} -Theme $Theme

Get-UDDashboard | Stop-UDDashboard
Start-UDDashboard -Dashboard $dashboard -Port 9984 -AutoReload
```

Thanks for any help!

**Comment by ChrisMagnuson** [comment]
@ericclaus14 I think the issue is that the `-Endpoint` script block gets executed in a its own runspace and doesn't necessarily have access to variables declared outside the runspace (though I feel like at times it does so it seems inconsistent.

Generally the right way to think of `-Endpoint` is like it is a totally separate powershell window.

In this case instead of passing things into that script block you could pull things you need from inside the script block.

In your case I believe a way to get this working would be to add a `$Session:CurrentVM = $VM` inside the foreach but outside the endpoint script block and then inside the endpoint scrip block do `$VM = $Session:CurrentVM`.

This only works if a single user never opens and refresh two tabs to the same dashboard at the same time. If that happened you would have a race condition and the value of `$Session:CurrentVM` would not be what is expected.

**Comment by ericclaus14** [comment]
Thanks for help, @ChrisMagnuson ! I hadn't thought about variable scopes. Your suggestion worked for me, only I had to change the scope from "Session" to "Global".
