### ISSUE TITLE
Variable matching within URL "Part"

### ISSUE THREAD

**Issue by rdbartram** [ironmansoftware/universal-dashboard#283]
I have a URL like /Nodes(AgentID='123')...if it looks familiar its because its from the DSC PullServer.

Currently you can only match whole "parts" unless the part is marked as variable i.e. is has a : at the start.

Would it be an option to change the IsMatch method to use regex matching or something in order to match a route similar to /Nodes(AgentID=':agentid{\d+}').

I am open to suggestions and maybe I missed something when going through the code here. However,  I'm pretty sure this isn't workable today.

Thanks for the help and suggestions.

**Comment by adamdriscoll** [comment]
I've considered changing URL matching for the 2.0 release. It's too basic. 

What'd I'd actually like to do is just utilize ASP.NET Core's routing system rather than the home brew one currently in UD. It's already available in the framework so it would make sense to take advantage of it. Some have complained that it's a bit complicated to configure but I think with some handy wrappers around it it could be pretty neat. 

Check it out and let me know if that would be helpful: https://docs.microsoft.com/en-us/aspnet/core/fundamentals/routing?view=aspnetcore-2.1

**Comment by rdbartram** [comment]
I like the idea, I sort of tried to borrow from it in my example above.

Would your idea be to keep the route maps as they currently are and introduce logic into the generic api actions that implement the URL Matcher or would you rather somehow try to dynamically create actions with route maps for each udendpoint?

**Comment by rdbartram** [comment]
I am playing with a routecollection in the configure method during startup. Then just looping the list of restendpoints in the executionservice and generating routes with go to the existing "generic" get, put, post and delete /api/* actions. I'll let you know how I get on

**Comment by adamdriscoll** [comment]
I don't mind introducing breaking changes for this as long as it makes sense to do so. Excited to see what you come up with!

**Comment by adamdriscoll** [comment]
Newer versions of UD can now use regex for this type of thing. It's actually been test with DSC PullServer.

**Comment by bgelens** [comment]
```powershell
New-UDEndpoint -Url "Nodes\(AgentId='(?<AgentId>.*)'\)" -Method PUT -Endpoint {
    param (
        $AgentId
    )
} -EvaluateUrlAsRegex
```
