### ISSUE TITLE
Support of standard HTTP response codes for Universal Dashboard REST API 

### ISSUE THREAD

**Issue by adamdriscoll** [ironmansoftware/universal-dashboard#32]
In case of error while running code from UD REST API endpoint, something like the following is returned :

error
-----
@{message=myCustomError; location=; type=error; id=; refreshInterval=0; autoRefresh=False; error=}

Is there a way to natively handle standard HTTP response codes as well ?

reference :  https://en.wikipedia.org/wiki/List_of_HTTP_status_codes

I would be great to be able to construct the returned object within the code with :
    - the return code
    - the return message
    - the content data (if any)

Thanks a lot for the answer and the great job done here.

Moved from: https://github.com/adamdriscoll/poshprotools/issues/202

**Comment by ChrisMagnuson** [comment]
The title of this issue appears to what I would add as a request but the body of this request seems to be asking for something else.

We are hitting an issue with sometimes code running in UD will throw an exception.

The client would properly handle this exception and try again if it got a failure status code like 500 but because UD responds with 200 even for errors the client doesn't retry and in our case ends up writing out a file containing the error text.

By default browsers will still show you the error text if a request gets a 500 response status code but powershell by default will not.

There are still ways to get 500 error text in PowerShell described [here](https://stackoverflow.com/questions/18771424/how-to-get-powershell-invoke-restmethod-to-return-body-of-http-500-code-response).

Can UD be updated to return 500 or another type of error status code when an exception is thrown causing execution to fail?

The below works as rough work around for this:

```
Get-UDRestApi | Stop-UDRestApi
$Port = 10000
$Endpoint = New-UDEndpoint -Url "/test" -Endpoint {
    try {
        throw {"error"} 
   } catch {
       $Response.StatusCode = 500
   }
}
Start-UDRestApi -Endpoint $Endpoint -Port $Port
iwr http://localhost:$Port/api/test
```

**Comment by adamdriscoll** [comment]
If you return an IActionResult from you endpoint, it will now return that instead of a 200. 

```
    $GetEndpoint = New-UDEndpoint -Url 'universal-automation/.*' -Method Get -EvaluateUrlAsRegex -Endpoint {
    [Microsoft.AspNetCore.Mvc.StatusCodeResult]::new(401)
    } -Public

```

**Comment by augiaugi** [comment]
@adam would be great to see this in the documentation

**Comment by adamdriscoll** [comment]
@augiaugi - I'll be doing a big doc refresh for v3 so this will be in there.

**Comment by xcabur1** [comment]
@adamdriscoll is there a new v3 doc about API http response code?
