### ISSUE TITLE
Any way to get new-uddashboard parameters values from inside another cmdlet?

### ISSUE THREAD

**Issue by AlonGvili** [ironmansoftware/universal-dashboard#365]
I'm working on add Icons8 Line Awesome font icon support to UD, but I'm stuck.

As I understand the icon part in ud split in 2, the command New-UDIcon that generate an HTML I tag with the font awesome class name, and the react component ud-icon.jsx.

basically, I want to add a new parameter to new-uddashboard  [  -FontIconStyle  ] that let you choose the style of the icons in ud its need to be applied to all components.

The part when a react component use ud-icon.jsx to generate an icon it is done and I tested it and its working.

but I can't figure out how to get the value of the FontIconStyle parameter from New-UDIcon.

Any Help will be appreciated.

**Comment by adamdriscoll** [comment]
I think what you can do is that since line-awesome supports a direct replacement of fontawesome without any other changes, you should be able to switch which CSS style sheet is imported based on your -FontIconStyle parameter. This currently happens in index.jsx.

https://github.com/ironmansoftware/universal-dashboard/blob/master/src/client/src/app/index.jsx#L8

You could remove that static import and then load the desired style sheet in dashboard.jsx using this function: https://github.com/ironmansoftware/universal-dashboard/blob/master/src/client/src/app/index.jsx#L8

Loading that data could happen in the loaddata function in that file. 

https://github.com/ironmansoftware/universal-dashboard/blob/master/src/client/src/app/index.jsx#L8

Then you shouldnt have to update ud-icon.jsx.

**Comment by adamdriscoll** [comment]
Closing due to your PR for the icons. Thanks again! That's awesome.
