### ISSUE TITLE
Module state not persisted to endpoint

### ISSUE THREAD

**Issue by ChrisMagnuson** [ironmansoftware/universal-dashboard#377]
We have modules that persist some basic state like a subdomain to be used when accessing a web service.

Example MyModule.psm1
```
function Set-Subdomain {
    param (
        $SubDomain
    )
    $Script:Subdomain = $SubDomain
}

function Invoke-Service {
    Invoke-WebRequest -Uri "$Script:SubDomain.example.com/service"
}
```

Previously we would use something like the following to initialize this module within the endpoint initialization script:
```
New-UDDashboard -EndpointInitializationScript {
    Set-Subdomain -SubDomain Something
}
```

With `New-UDEndpointInitialization` the `-Module` parameter [only tells the endpoints runspace to import the named module](https://github.com/ironmansoftware/universal-dashboard/blob/master/src/UniversalDashboard/Cmdlets/NewEndpointInitializationCommand.cs#L33) which doesn't bring in the current configured state of the module.

`-Variable` and `-Function` don't help with this either.

Unless there is a way to bring along a module's current state then we would need `New-UDEndpointInitialization` to have a `-ScriptBlock` parameter or something like that so that we can reinitialize the state of our modules within the endpoint.

**Comment by adamdriscoll** [comment]
Ah, interesting. Ok. Something I hadn't thought of. This change was made to enable the reset of runspace state per execution. The previous problem was that variables would be left behind between endpoint execution which is leaky, dangerous behavior. 

Now per execution the runspace state is reset to the Initial Session State created via the New-UDEndpointInitialization cmdlet. 

https://github.com/ironmansoftware/universal-dashboard/blob/51a7cf334ad9f98d872b33dc2a062d8cc63e3fa9/src/UniversalDashboard/Execution/ExecutionService.cs#L92

I'll have to look into this more because I'm not sure what a good solution is yet. I'm not seeing anything in the InitialSessionState class that helps with this: https://docs.microsoft.com/en-us/dotnet/api/system.management.automation.runspaces.initialsessionstate?view=powershellsdk-1.1.0

**Comment by ChrisMagnuson** [comment]
I am looking again at updating one of our apps to use the new UD and I was thinking about generating a script module that initializes the state of all the other modules immediately (no functions in the initialization module, just commands that execute upon module import).

I think I could do something like this and then use the `-Module` parameter to import this module that when imported initializes the other modules.

Feels a bit like a kludge but might be a good option for anyone generically needing something like the `-EndpointInitializationScript` behavior or even something that could be baked in, if someone specifies `-EndpointInitializationScript` you take that script block, drop it to a module, and then implicitly import that module along with anything specified with `-Module`.

**Comment by ChrisMagnuson** [comment]
I now use code like the following to get the same effect as the previously available `-EndpointInitializationScript`:
```
EndpointInitializationScript |
Set-Content -Path .\InitilizationModule.psm1

$InitilizationModuleFullName = Get-Item -Path .\InitilizationModule.psm1 |
Select-Object -ExpandProperty FullName

$EndpointInitialization = New-UDEndpointInitialization -Module @( $InitilizationModuleFullName )

Start-UDRestApi -Endpoint $Endpoint -EndpointInitialization $EndpointInitialization -Wait
```

Works the same with `Start-UDDashBoard`.

If something like this could be implemented internal to UD that would be great so that this pattern doesn't have to be repeated in each dashboard/endpoint.
