### ISSUE TITLE
UDButton to create dynamic pages

### ISSUE THREAD

**Issue by nicoeat614** [ironmansoftware/universal-dashboard#443]
Can someone help me out with this? I have gotten to the point where I am just totally lost and confused myself. I have been reading every documentation out there and look for examples but I am just lost. 

I am trying to create a dynamic page based on UDButton click and it's not working. I don't know if it is due to my variable scoping, the cmdlets I am using, or whatever but I am just confused and been going at this for a week now. 

Here is my json data on github: [VAJSON](https://github.com/nicoeat614/UDTesting/blob/master/UDTestData.json)
And here is my obviously horrible script on github:[VAScript](https://github.com/nicoeat614/UDTesting/blob/master/Get-VAScratchData.ps1)

Any help would be appreciated. Adam, you need a forum for this! Awesome product!!

**Comment by adamdriscoll** [comment]
@nicoeat614 A forum is a good idea. ;) 

Can you provide some example code of what you're trying to do?

**Comment by AlonGvili** [comment]
I was looking into @nicoeat614  files and for hours I was trying to make ud-button to invoke dynamic page with no success.
when using on click property in ud-button it seems that it not seeing the value of a variable if it inside ud-card that inside the loop
if I move the button outside the card or the loop the button will work.
I think its problem with the variable scope

**Comment by adamdriscoll** [comment]
Ack. I totally overlooked the code files. I can take a look.

**Comment by AlonGvili** [comment]
I hope that you can make this to work

**Comment by adamdriscoll** [comment]
I figured out the button issue. It is a variable scoping problem. [In 2.0, I added this syntax](https://docs.universaldashboard.io/updates/v2.0.0#improved-endpoint-arguments)
: 

```
 New-UDButton -Id "$($item.name + '_info')" -Icon plus -Floating -IconAlignment right -OnClick (New-UDEndpoint -Endpoint {                                 
                                Invoke-UDRedirect -Url  "/Scratcher/$($ArgumentList[0])/$($ArgumentList[1])" 
                                                                              } -ArgumentList @($dropdown, $item.name))
                                                                    } 
                                                        }
                                            }
                                }
```

Rather than "automatically" pulling in the variables into scope, instead we use the ArgumentList parameter. This is a lot more consistent than the automatic scoping for whatever reason. 

Attached is the full script. 

[Get-VAScratchData.zip](https://github.com/ironmansoftware/universal-dashboard/files/2558709/Get-VAScratchData.zip)

There is a problem with the URLs for dynamic pages where both controls are showing up at once: 

![image](https://user-images.githubusercontent.com/1256531/48152552-cc40dd00-e289-11e8-87c6-113d79fb58a8.png)

**Comment by AlonGvili** [comment]
> I figured out the button issue. It is a variable scoping problem. [In 2.0, I added this syntax](https://docs.universaldashboard.io/updates/v2.0.0#improved-endpoint-arguments)
> :
> 
> ```
>  New-UDButton -Id "$($item.name + '_info')" -Icon plus -Floating -IconAlignment right -OnClick (New-UDEndpoint -Endpoint {                                 
>                                 Invoke-UDRedirect -Url  "/Scratcher/$($ArgumentList[0])/$($ArgumentList[1])" 
>                                                                               } -ArgumentList @($dropdown, $item.name))
>                                                                     } 
>                                                         }
>                                             }
>                                 }
> ```
> Rather than "automatically" pulling in the variables into scope, instead we use the ArgumentList parameter. This is a lot more consistent than the automatic scoping for whatever reason.
> 
> Attached is the full script.
> 
> [Get-VAScratchData.zip](https://github.com/ironmansoftware/universal-dashboard/files/2558709/Get-VAScratchData.zip)
> 
> There is a problem with the URLs for dynamic pages where both controls are showing up at once:
> 
> ![image](https://user-images.githubusercontent.com/1256531/48152552-cc40dd00-e289-11e8-87c6-113d79fb58a8.png)

And that is why your the MAN

**Comment by adamdriscoll** [comment]
I added docs to better outline this: https://docs.universaldashboard.io/endpoints/event-handler-endpoints

**Comment by AlonGvili** [comment]
Thank you

**Comment by nicoeat614** [comment]
Thank you both @adamdriscoll  and @AlonGvili  for getting back to me. I thought I was well-seasoned in PowerShell but PUD definitely makes you go back to the drawing board and clean up your laziness in scripting. The variable scoping is serious business. 

As you mentioned Adam, "there is a problem with the URLs for dynamic pages where both controls are showing up at once."  Under your [dynamic pages](https://docs.universaldashboard.io/components/pages) section in the Pages article, it states that you can have multiple variables in a route: **New-UDPage -Url "/myPage/:number/:number2"**. I was under the impression that this could be used to show some type of hierarchy, such as a file system path and create another dynamic page (which you saw in my code). Instead, it's like taking the dynamic pages and combining them together. 

Also, in the code you provided me (snippets): 
```
$Global:DynamicPage = New-UDPage -Url "/Scratcher/:dropdown" -Endpoint {
                            param($dropdown, $scratchref)
Invoke-UDRedirect -Url  "/Scratcher/$($ArgumentList[0])/$($ArgumentList[1])" 
                                                                              } -ArgumentList @($dropdown, $item.name))
                                                             }
#Dynamic Page for UDButton url redirect
$Global:ScratcherPage = New-UDPage -Url "/Scratcher/:state/:scratchref" -Endpoint {
        param($state, $scratchref)                                                                   
```
How come this somewhat work, even though $item.name isn't part of any param block? I was trying to set $scratchref to $item.name and pass it that way but it's comes out as if $scratchref is null. I can't get it to pass through the different runspaces. 

Thanks again to both and Adam, keep up the good work. I bought PowerShell Pro Tools back in March.  Love it!! (shameless request: add the functionality for Posh Tools to detect and scale based on the OS' DPI).

**Comment by adamdriscoll** [comment]
@nicoeat614 You should be able to have multiple variables in the route. I will have to look into why this is happening with the dynamic page. 

For the variable scoping, the reason this works is because the automatic scoping is working in this circumstance. If you want consistent variable scoping, I would suggest the manual method from the docs using `-ArgumentList`. 

The long version is that because you are creating static components in that foreach loop (the one that produces the $item variable), this will work. It doesnt need to create a new variable scope for the UDCard or UDParagraphs. But when you got to create the UDButton that uses an OnClick event handler, it has to create a new endpoint which has a new variable scope. Sometimes automatic scoping will work here but usually when using a loop variable like this, it doesn't work for whatever some internal reason with the PowerShell engine. The `-ArgumentList` works around that and seems to work in all circumstances which is why I'm recommending it going forward (even if it's a bit more typing 👎 )

**Comment by adamdriscoll** [comment]
Also! I created a forum per your request: https://forums.universaldashboard.io/

🥇

**Comment by adamdriscoll** [comment]
I just merged a PR that should fix your issue with dynamic pages showing 2 pages at once: https://github.com/ironmansoftware/universal-dashboard/pull/453

I will properly document this but you will need to include the more specific page URL fix. The idea being that UD will pick the fix matched page. 

For example, you'd have to change your code like this: 

```
-Pages @($HomePage, $Global:ScratcherPage, $Global:DynamicPage)
```
