### ISSUE TITLE
Question about an Endpoint

### ISSUE THREAD

**Issue by LaurentDardenne** [ironmansoftware/universal-dashboard#502]
Can an Endpoint contains multiple calls to the write-output cmdlet?
```Powershell
$Endpoint = New-UDEndpoint -Url "Test" -Method "GET" -Endpoint {
 Write-output "First call"
 Write-output "Second call"
}
Start-UDRestApi -Endpoint $Endpoint -wait
```
The call
```Powershell
Invoke-RestMethod -Uri http://localhost:1000/api/Test
#First call
```
The second value is not received.
 
And does the Write-output call 'automatically' populate the _Body_ property of the _**$Response**_ variable of UD?

**Comment by adamdriscoll** [comment]
The problem is that UD is selecting the first item: https://github.com/ironmansoftware/universal-dashboard/blob/master/src/UniversalDashboard/Execution/ExecutionService.cs#L158

I would argue that that is a bug. As a work around, you might be able to return them as an array. 

```
@(Write-Output "First Call"; Write-Output "Second Call")
```

UD does automatically populate the Body property but through the ASP.NET Json method.

https://github.com/ironmansoftware/universal-dashboard/blob/master/src/UniversalDashboard/Controllers/ComponentController.cs#L93

**Comment by LaurentDardenne** [comment]
_I would argue that that is a bug._
I think so too.

_As a work around, you might be able to return them as an array._
It was just for highlighting. In my context I do not think it's possible.
But now I know this limit :-)

_UD does automatically populate the Body property_ 
Maybe explain (explicit) this in the documentation.

Thanks.
