### ISSUE TITLE
Doughnut chart not displaying when published in IIS

### ISSUE THREAD

**Issue by psDevUK** [ironmansoftware/universal-dashboard#516]
So I created a semi circle doughnut chart which displayed without issues when I was building the dashboard and testing it.  I then published it to IIS and I have multiple other sites running universal dashboards and do display charts.  But this was my first doughnut chart I was using. However after publishing the dashboard to IIS when visiting it, it no longer displayed the semi circle doughnut chart? I tried this on 2.1.0 and 2.2.0 and same result. Running the dashboard when not published in IIS displays semi circle doughnut chart without issues.  Can anyone help me out?

**Comment by PorreKaj** [comment]
I've done something similar that has send me running in circles troubleshooting.

If the data is from any external source (well external as in outside the dashboard, like AD or a database), are you sure the ISS service has access? Running a dashboard in powershell executes it with your credentials. but with the app pool identity.

To confirm i usually add a UdGrid to pass the data to in order to verify it.

**Comment by PorreKaj** [comment]
Also, theres a forum here that does help: https://forums.universaldashboard.io/c/help
I'm not sure i'd call your problem an 'issue' just yet :-)

**Comment by psDevUK** [comment]
Yep it was my code....doh! So please close this issue as it is not an issue,  Thanks @PorreKaj for suggestions.

**Comment by psDevUK** [comment]
Sorry for opening this as an issue, it was an issue with my code.
