### ISSUE TITLE
Dynamic Page is Blank

### ISSUE THREAD

**Issue by adamdriscoll** [ironmansoftware/universal-dashboard#626]

**Comment by dtnyc9005** [comment]
@adamdriscoll not sure if this is also related but inside a grid when creating a New-UDLink to dynamic page, I also see a blank page. (currently running Windows PS 5.1 w/ UD: 2.3.1),

Another thing noticed is why when calling the dynamic page directly its also blank, is this by design?

       $cache:Data = @(foreach ($item in $cache:Importdata) {

            [pscustomobject]@{
                Hostnames = (New-UDLink -Text $item.hostnames -Url "/dynamic-computer/$($item.hostnames)" -OpenInNewWindow -FontColor 'white')
                Department   = $item.Department
                Comment      = $item.Comment    
                Category     = $item.Category
                AdminContact = $item.admincontact
                TYPE         = $item.type
            }

        }
    
    )


thanks again.
