### ISSUE TITLE
Changing background color dynamically for UDCounter

### ISSUE THREAD

**Issue by emrgcl** [ironmansoftware/universal-dashboard#630]
Hi,

It would be great if we can change the colors (bg & font) of the udcounter depending on the result of the Endpoint to highlight the thresholds.

If thres such sample I wasnt able to find in the document if so updating the documentation would do great help.

Kind Regards,
Emre

**Comment by adamdriscoll** [comment]
You could probably achieve this with New-UDElement or new New-UDCard (which has a backgroundColor parameter). 

Then rather than AutoRefresh on the counter, you can autoRefresh the row containing the card\element. 

```
New-UDRow -Endpoint {
    New-UDColumn -Content {
          New-UDCard -BackgroundColor "black"
    }
}
```

I'll mark this as an enhancement though as it would be a good feature for the UDCounter to have.

**Comment by DWOF** [comment]
I'm trying to achieve the same. Thank you for the workaround I shall give it a shot.

**Comment by emrgcl** [comment]
It perfectly worked for me! Thanks a lot!

`
New-UDRow -AutoRefresh -RefreshInterval 5 -Endpoint {
$Random = (Get-Random -Maximum 2)    
    $BGColor = "Red","Yellow"
    New-UDColumn -Content {
              New-UDCard -BackgroundColor $BGColor[$Random]
    }
}
`
