### ISSUE TITLE
IIS Authorization Policy Does Not Work [2.3.1]

### ISSUE THREAD

**Issue by adamdriscoll** [ironmansoftware/universal-dashboard#640]
When I change $ClaimsPrinciple to $ClaimsPrincipal in my UDAuthorizationPolicy, I can now see the secured pages in the hamburger menu. (I thought you were going to leave that backwards compatible, but that’s okay; I don’t mind spelling it right.)

But the secured page does not work. I do have the navbar and footer bar, but there is nothing in between.

This page behaves normally:

New-UDPage `
    -Name 'Potato1' `
    -Content { New-UDHeading -Text 'Just testing' }
This page has no content (other than the NavBar):

New-UDPage `
    -Name 'Potato2' `
    -Content { New-UDHeading -Text 'Just testing' } `
    -AuthorizationPolicy 'AdminGroup'

**Comment by TimCurwick** [comment]
Thanks, Adam.

I hadn't opened it myself yet, because I was trying to put together better reproduction steps, but I can't reproduce the behavior I originally described.

I can't get it to work at all.  I.e. - I'm not getting the secured page showing up in the hamburger menu like I thought it was the other day.

The relevant line in the debug log would seem to be:
14:07:34 [Warn] DashboardController Failed to evaluate authorization policy. There is no Runspace available to run scripts in this thread. You can provide one in the DefaultRunspace property of the System.Management.Automation.Runspaces.Runspace type.
