### ISSUE TITLE
New-UDChart -Type Line does not return Label property

### ISSUE THREAD

**Issue by mkellerman** [ironmansoftware/universal-dashboard#658]
EventData returned by Line chart on click:
````
[{"x":953.021484375,"y":46.18285714285713,"skip":false,"radius":4,"pointStyle":"circle","backgroundColor":"rgb(245, 69, 0)","borderColor":"rgb(0, 0, 0)","borderWidth":1,"tension":0.4,"hitRadius":1,"controlPointPreviousX":914.2563423484957,"controlPointPreviousY":32.91988146963996,"controlPointNextX":1006.2563423484957,"controlPointNextY":64.39645289821138}]
````
Compared to a Bar Chart:
````
 [{"datasetLabel":"","label":"15:00","borderSkipped":"bottom","backgroundColor":"rgba(255, 159, 13, 1)","borderColor":"rgba(123, 33, 12, 1)","borderWidth":1,"horizontal":false,"base":382.7142857142857,"x":1125.34765625,"y":131.57142857142858,"width":34.56000000000001}]
````

**Comment by mkellerman** [comment]
Would be good to keep things consistent on all the charts.

**Comment by adamdriscoll** [comment]
This is coming from ChartJS directly so it'll be a little tricky to add but I can look into it.

**Comment by GregorSm** [comment]
Me and another guy on [Universal Dashboard Forums](https://forums.universaldashboard.io/t/getting-useful-information-from-eventdata-in-udchart-onclick/571
) also need this fixed. $EventData should return data from the dataset corresponding to the point clicked so that we can implement drill-down scenarios.
