### ISSUE TITLE
Allow UDInput/UDInputField formating

### ISSUE THREAD

**Issue by mkellerman** [ironmansoftware/universal-dashboard#744]
Would be nice to format the input fields. Is there a way? This is what i tried:

````powershell
New-UDInput -Title 'Database Search' -Content {

    New-UDRow {
        New-UDColumn {
            New-UDInputField -Type 'textbox' -Name 'SearchTerm' -Placeholder 'Search your projects for free form text'
        }
    }
    New-UDRow {
        New-UDColumn {
            New-UDInputField -Type date -Name "StartDate" -Placeholder "Start Date (00:00)"
        }
        New-UDColumn {
            New-UDInputField -Type date -Name "EndDate" -Placeholder "End Date (23:59)"
        }
    }    

} -Endpoint {
    param($Keyword, $StartDate, $EndDate)
}
````

Unfortunately, all my input fields disappear when i do this.

**Comment by adamdriscoll** [comment]
Not at the moment but we could make this happen.

**Comment by mkellerman** [comment]
Is it something I would be able to figure out in the source myself?

**Comment by adamdriscoll** [comment]
Maybe. Looking at the code it's a little tricky because the ud-input.jsx file is expecting a list of fields so that it can format them correctly. With the formatting involved, they aren't just a list of fields so we'd have to do some weirdness with deserialization or something on the client side. 

It's honestly a bit of work.

**Comment by adamdriscoll** [comment]
Just merged New-UDForm which supports this scenario.
