### ISSUE TITLE
Not all icons works (User_Cog)

### ISSUE THREAD

**Issue by PorreKaj** [ironmansoftware/universal-dashboard#806]
If I set the -icon on a new-uddashboard to User_cog, the page dissappears from the site (not visible in the hamburger menu, nor accessible through the url)

I've seen this with other icons, but just at the top of my head I can only remember the User_Cog.

on 2.4.0 btw.

Doesn't work:
`New-UDPage -Name "Admin - Employees" -AuthorizationPolicy @("EmployeesAdmin") -Icon user_cog -Content {}`

Works:
`New-UDPage -Name "Admin - Employees" -AuthorizationPolicy @("EmployeesAdmin") -Icon user -Content {}`

**Comment by adamdriscoll** [comment]
This has been fixed in 2.4 GA. I mapped all the FontAwesome 4.7 icon names to the equivalent FontAwesome 5.0 icon names so it should all work. 

Just tested your icon to be sure. If you run into any more icons that exhibit this behavior, please open another issue. 

![image](https://user-images.githubusercontent.com/1256531/58173484-be1c4200-7c58-11e9-8c37-4c6eefa85aca.png)

**Comment by adamdriscoll** [comment]
Also, 2.4 is now on the gallery.
