### ISSUE TITLE
Nivo axis/text color

### ISSUE THREAD

**Issue by jello3d** [ironmansoftware/universal-dashboard#851]
Hopefully this is a stupid question - 

How does one change the axis text, or grid color?

Thanks

**Comment by psDevUK** [comment]
There is some info here on setting colours:-
 https://docs.universaldashboard.io/components/data-visualizations/nivo#creating-a-nivo-chart
and some more info here:-
https://docs.universaldashboard.io/updates/v2.2.0-beta2#new-color-options
  Hopefully this answers your question?

**Comment by jello3d** [comment]
I appreciate your time, but I don't see anything about text/grid color in the ud instructions, nor even on the Nivo site... Hence my confusion.  

Seems like an odd thing to have no control over.  On a dark theme you can't see anything.

**Comment by psDevUK** [comment]
ok I found issues in IE, and I think off memory I was using 2.3.0 at the time and had issue in IE with dark theme...so here is how I am doing a heatmap from a text file which has been generated via a scheduled task pulling data from SQL
`$content2 = (get-content $PSScriptRoot\breadfinal.txt | Out-String)
$data9 = @(invoke-expression $content2)
[array]$nodes = get-content $PSScriptRoot\dates.txt
New-UDNivoChart -Colors 'blues'  -Heatmap -Data $($data9) -IndexBy 'productname' -keys @($nodes)  -Height 1200 -Width 2000 -MarginTop 20 -MarginRight 130 -MarginBottom 50 -MarginLeft 130 -MinValue 0 -MaxValue 30`
  Notice the -Colors parameter this then sets the heatmap in a blue theme instead of the default colour scheme.  I have an example of this dashboard in action here:-
 https://forums.universaldashboard.io/t/dashboard-to-show-orders-placed-from-sql-db/663
this is using the default color scheme, but you can adjust the shades displayed using the -MinValue and -MaxValue parameters. Hope this helps?

**Comment by psDevUK** [comment]
sorry the -indexby parameter set my products going down the chart and the dates along the top using -keys parameter you should see this on the link I posted.  I just found it difficult to get the data in the array format it had to be in for the chart to read the data properly

**Comment by jello3d** [comment]
But none of that changes the text color for the the axis values/labels... right?  My problem is that on a dark, or dark grey them, all the labels along the axes tend to disappear, because all that text is rgb 51,51,51 and I can't seem to change it.  The -colors themes don't seem to have any effect on text color.

**Comment by adamdriscoll** [comment]
Can you let me know what charts you are using? It looks like I need to hook up some of the color options for nivo charts in UD.

**Comment by jello3d** [comment]
Doesn't seem to matter which chart, none appear to have options for axis text or grid colors... I don't even see how you would change the colors on the nivo site.  maybe it's supposed to change automatically based on the page background color and that isn't exposed in UD?

in the specific example i'm playing with now, it's a line chart

**Comment by jello3d** [comment]
I should also mention that if i add the -responsive switch, the chart disappears.

``            $BottomAxis = New-UDNivoChartAxisOptions -TickRotation '60'
            New-UDNivoChart -Colors 'nivo' -Line -Data $Data -Height 400 -Width 900 -Curve catmullRom -UseDataColor -EnableArea -MarginBottom 200 -AxisBottom $BottomAxis -Marginleft 50 -AreaOpacity .4
``

**Comment by adamdriscoll** [comment]
I've noticed that label colors options are now present for bar and heatmap charts but not for line charts in the nivo framework. I think I'll open an issue on that repo to see what's happening. 

I'll see if I can figure out what's happening with the responsive switch. I'll be updating this to the latest Nivo package for the next release so hopefully we will see some issues resolved.

**Comment by adamdriscoll** [comment]
I figured the tick color configuration out. I'll get it out in the next kit.

**Comment by adamdriscoll** [comment]
This will be implemented in tonight's build. You can now use the `New-UDNivoTheme` command to set the tick and grid color. 

```
$Theme = New-UDNivoTheme -TickTextColor 'red'

            $Parameters = @{
                Data = $Data
                Height = 500
                Width = 1000
                MarginTop = 50
                MarginRight = 130
                MarginBottom = 50
                MarginLeft = 60
                Theme = $Theme
            }

            New-UDNivoChart -Line @Parameters
```

![image](https://user-images.githubusercontent.com/1256531/58851475-26532680-8650-11e9-9740-b3955a692014.png)

Opening a separate issue for the responsive switch not working.
