### ISSUE TITLE
Enhancement spinner (loading) button for tasks that take a long time

### ISSUE THREAD

**Issue by psDevUK** [ironmansoftware/universal-dashboard#871]
Hi @adamdriscoll  I have been speaking with @wsl2001 on: 
https://forums.universaldashboard.io/t/changing-the-button-behavior-onclick/785/4 
and I was thinking this is the solution:
https://github.com/simformsolutions/react-native-spinner-button 
I am going to try and do this myself and if successful upload the code, but I know you could do this, plus would be a great demo, as I see you changed the custom component file a bit from the youtube vid.  As mentioned this would be a super cool enhancement for long running tasks to stop the user keep clicking the button, and show feedback to the user it's busy.

**Comment by adamdriscoll** [comment]
I think we should consider enhancing UDButton rather than implementing a new button. FontAwesome has spinner icons we can use to put inside the existing button and disable it. I can play around with it tomorrow to see if there is a way to handle that with the current code-base but otherwise, we can look at updating the React component in UD.

**Comment by adamdriscoll** [comment]
@psDevUK - I take back what I said and for this use-case, I'm just going to suggest the button you created: https://marketplace.universaldashboard.io/Dashboard/UniversalDashboard.UDButtonLoader
