### ISSUE TITLE
Getting a spam of the same error - Microsoft.AspNetCore.Server.Kestrel

### ISSUE THREAD

**Issue by Phyziik** [ironmansoftware/universal-dashboard#88]
When I run my dashboard, I constantly get : 

> 09:31:41 Microsoft.AspNetCore.Server.Kestrel Connection id "0HLD93LBFEH2B", Request id "0HLD93LBFEH2B:0000006A": An unhandled exception was thrown by the application

Not really sure how to debug the source of that issue, and if it's coming from me or not.

Thanks

**Comment by bgelens** [comment]
@adamdriscoll, I have the same thing, turns out it happens because nothing is returned which is a valid scenario in my opinion.

Consider this

```powershell
if ($found) {
  $Response.StatusCode = 204 # ok, no content
} else {
  $Response.StatusCode = 404
  'not found'
}
```

Because nothing is casted when if is true, the error is thrown and captured in the logging. I think 204 without content should be handled correctly though.

To workaround the issue, just have an empty string (which still is content IMO)
