### ISSUE TITLE
New-UDMapPopup only width scales for first Line of Content

### ISSUE THREAD

**Issue by leeberg** [ironmansoftware/universal-dashboard#933]
I have been experiementing with New-UDMapPopup and trying to show A LOT of content in my popups. I seem to be having some problems with the max-width scaling properly...

Consider the following test:

``` powershell
 New-UDMapOverlay -Name 'test' -Content {
                    New-UDMapMarker -Latitude '43.0730553' -Longitude '-89.4569855' -Popup (New-UDMapPopup -Content {
                        
                        New-UDRow {   
                            New-UDHeading -Size 1 -Text ("Bus: $($Vehicle.VehicleLabel)")
                        }
                        New-UDRow {   
                            New-UDHeading -Text ("Time: $($Vehicle.TimeCurrent)")
                        }
                        New-UDRow {   
                            New-UDHeading -Text ("Route: $($Vehicle.RouteID)")
                        }
                        New-UDRow {   
                            New-UDHeading -Text ("Trip: $($Vehicle.TripID)")
                        }
                       
                        New-UDRow -Columns {            
                            New-UDColumn -Size 4 {
                                New-UDHtml -Markup "<h1>Column 1 </h1>"
                            }
                            New-UDColumn -Size 4 {
                                New-UDHtml -Markup "<h1>Column 2 </h1>"
                            }      
                            
                            New-UDColumn -Size 4 {
                                New-UDHtml -Markup "<h1>Column 3 </h1>"
                            }   
                        }              

                        New-UDImage -Url 'https://media1.giphy.com/media/J1ZajKJKzD0PK/giphy.gif?cid=790b76115d1c03c92f6655656b893446&rid=giphy.gif'

                        } -MaxWidth 1000 )
                } -Checked 
```

Height Scaling is working like a champ - but it seems like I am having a hard stop maxwidth...

![image](https://user-images.githubusercontent.com/274883/60556737-40902b00-9d08-11e9-9f1e-fb800a8b3963.png)

Turns out if I make the VERY FIRST item in my popup a long width is DOES Scale:
![image](https://user-images.githubusercontent.com/274883/60556827-91a01f00-9d08-11e9-98ce-27a5873b770e.png)

**Comment by adamdriscoll** [comment]
This is actually a problem with column sizing. Since you are using UDColumns -Size 4 for your columns, they will be 33.33% of their parent container. The parent container is changing it's size based on the content. The only thing in your popup that is forcing the width of the popup to change is the first line. That means that your columns will be squished when they are shown. 

The way I've fixed this is to add a MinWidth parameter to New-UDMapPopup. This will allow you to set a minWidth to something like 1000 and avoid the squishing. You probably could also work around this with some CSS\New-UDElement futzing as well.
