### ISSUE TITLE
UDButton Attributes are not working

### ISSUE THREAD

**Issue by SConstantinou** [ironmansoftware/universal-dashboard#978]
Button attributes are not working on 2.5.2 as before.

I had the below code when I was using 2.3.2 and it was working. After upgrading to 2.5.2, it stopped working

```
if ($SetupIP -eq 'Offline')
    {
        $LoginButton = New-UDButton -Floating -Icon sign_in
        $LoginButton.Attributes.target = "_blank"
        $LoginButton.Attributes.rel = "noopener noreferrer"
        $LoginButton.Attributes.href = "http://$SetupIP"
        $LoginButton.Attributes.disabled = "true"
        $LoginButton
    }
else
    {
        $LoginButton = New-UDButton -Floating -Icon sign_in
        $LoginButton.Attributes.target = "_blank"
        $LoginButton.Attributes.rel = "noopener noreferrer"
        $LoginButton.Attributes.href = "http://$SetupIP"
        $LoginButton
    }
```

**Comment by leeberg** [comment]
Hey @SConstantinou - it does indeed seem like the New-UDButton completely lost its attribute values in #816 - certainly a breaking change in this case.

We'll go and review to ensure this was intentional but in the meantime for your case what you'll need to do in this case is to handle your intended action inside a script block by appending the "-OnClick" to your New-UDButton. 

This allows you to define a script block to decide what happens when the button is clicked. In your case I would also utilize the "Invoke-UDRedirect" command that allow redirection action into the script block.

Below is a sample script and some docs on the updated cmdlets:

[Button Docs](https://adamdriscoll.gitbooks.io/powershell-universal-dashboard/components/button.html)

[New-UDButton API Doc](https://github.com/ironmansoftware/universal-dashboard-documentation/blob/master/api/New-UDButton.md)

[Invoke-UDRedirect Docs](https://github.com/ironmansoftware/universal-dashboard-documentation/blob/master/api/Invoke-UDRedirect.md)

``` powershell
 $SetupIP = "ImOnlineBaybee"

    if ($SetupIP -eq 'Offline')
    {
        $LoginButton = New-UDButton -Floating -Icon sign_out -OnClick{
            Invoke-UDRedirect -Url "https://www.google.com" 
        }
        $LoginButton 
    }
    else
    {
        $LoginButton = New-UDButton -Floating -Icon sign_in -OnClick{
            Invoke-UDRedirect -Url "https://www.google.com" -OpenInNewWindow
        }
        $LoginButton 
    }
```

Please let me know if this will work for you. I'll go ahead and setup an enhancement on the backlog if this isn't working out for you or if this is major problem for you.

**Comment by SConstantinou** [comment]
Hello Lee,

Thank you for the information. This works for me. I had to do the below in
order to work.

if ($SetupIP -eq 'Offline')
    {
        $LoginButton = New-UDButton -Floating -Icon sign_in
        $LoginButton.disabled = "true"
        $LoginButton
    }
else
    {
        $LoginButton = New-UDButton -Floating -Icon sign_in -OnClick (
            New-UDEndpoint -Endpoint {
                $LoginIP = $ArgumentList[0]
                Invoke-UDRedirect -Url "http://$LoginIP" -OpenInNewWindow
            } -ArgumentList @($SetupIP)
        )
        $LoginButton
}

Thank you
Stephanos Constantinou
www.sconstantinou.com

**Comment by SConstantinou** [comment]
I have tested it locally, although. I need to check it on IIS.

Thank you
Stephanos Constantinou
www.sconstantinou.com

**Comment by adamdriscoll** [comment]
@leeberg This wasn't intentional. I changed UDButton from using New-UDElement under the covers to using the react-materialize button component. I can add the attributes back in a PR for 2.5.3 tomorrow. 

Sorry about that!

**Comment by adamdriscoll** [comment]
Fixed with https://github.com/ironmansoftware/universal-dashboard/pull/1342
